version: '3'
services:
  bot:
    container_name: 'telegram-crypto-bot'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app/'
      - '/app/node_modules/'
    ports:
      - 3000:3000
    restart: always
    tty: true
